ALTER TABLE `CNAM_Attendance_DB`.`Lecture` 
ADD INDEX `FK_Lecture_PERIOD_PERIODCODE_idx` (`PERIOD_PERIODCODE` ASC);
ALTER TABLE `CNAM_Attendance_DB`.`Lecture` 
ADD CONSTRAINT `FK_Lecture_PERIOD_PERIODCODE`
  FOREIGN KEY (`PERIOD_PERIODCODE`)
  REFERENCES `CNAM_Attendance_DB`.`PERIOD` (`PERIODCODE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


ALTER TABLE `CNAM_Attendance_DB`.`Lecture` 
ADD COLUMN `CLASSROOM_CLASSROOM_ID` BIGINT(20) NULL AFTER `PERIOD_PERIODCODE`;


ALTER TABLE `CNAM_Attendance_DB`.`Lecture` 
CHANGE COLUMN `CLASSROOM_CLASSROOM_ID` `CLASSROOM_CLASSROOM_ID` BIGINT(20) NULL DEFAULT NULL ,
ADD INDEX `FK_Lecture_CLASSROOM_CLASSROOM_ID_idx` (`CLASSROOM_CLASSROOM_ID` ASC);
ALTER TABLE `CNAM_Attendance_DB`.`Lecture` 
ADD CONSTRAINT `FK_Lecture_CLASSROOM_CLASSROOM_ID`
  FOREIGN KEY (`CLASSROOM_CLASSROOM_ID`)
  REFERENCES `CNAM_Attendance_DB`.`CLASSROOM` (`CLASSROOM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
