ALTER TABLE `CNAM_Attendance_DB`.`Lecture` 
ADD INDEX `FK_Lecture_PERIOD_PERIODCODE_idx` (`PERIOD_PERIODCODE` ASC);
ALTER TABLE `CNAM_Attendance_DB`.`Lecture` 
ADD CONSTRAINT `FK_Lecture_PERIOD_PERIODCODE`
  FOREIGN KEY (`PERIOD_PERIODCODE`)
  REFERENCES `CNAM_Attendance_DB`.`PERIOD` (`PERIODCODE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
