CREATE TABLE `CNAM_Attendance_DB`.`ATT_PARAMETERS` (
  `PARAMETERS_ID` INT NOT NULL,
  `ISSAE_LATITUDE` DECIMAL(26,20) NOT NULL,
  `ISSAE_LONGITUDE` DECIMAL(26,20) NOT NULL,
  `GOOGLE_MAPS_API` VARCHAR(200) NOT NULL,
  `ACTIVE_FLG` INT(1) NOT NULL,
  PRIMARY KEY (`PARAMETERS_ID`));
