CREATE DATABASE IF NOT EXISTS CNAM_Attendance_DB;
USE CNAM_Attendance_DB;



CREATE TABLE `Attendance` (
  `ATTENDANCE_ID` bigint(20) NOT NULL,
  `PRESENT` tinyint(1) DEFAULT '0',
  `LECTURE_LECTURE_ID` bigint(20) DEFAULT NULL,
  `PERSON_PERSON_ID` bigint(20) DEFAULT NULL,
  `LATITUDE` decimal(26,20) DEFAULT NULL,
  `LONGITUDE` decimal(26,20) DEFAULT NULL,
  PRIMARY KEY (`ATTENDANCE_ID`),
  UNIQUE KEY `UNQ_Attendance_0` (`LECTURE_LECTURE_ID`,`PERSON_PERSON_ID`),
  KEY `FK_Attendance_PERSON_PERSON_ID` (`PERSON_PERSON_ID`),
  CONSTRAINT `FK_Attendance_LECTURE_LECTURE_ID` FOREIGN KEY (`LECTURE_LECTURE_ID`) REFERENCES `Lecture` (`LECTURE_ID`),
  CONSTRAINT `FK_Attendance_PERSON_PERSON_ID` FOREIGN KEY (`PERSON_PERSON_ID`) REFERENCES `PERSON` (`PERSON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CLASSROOM` (
  `CLASSROOM_ID` bigint(20) NOT NULL,
  `CLASSROOMNAME` varchar(255) NOT NULL,
  `LATITUDE` decimal(26,20) DEFAULT NULL,
  `LONGITUDE` decimal(26,20) DEFAULT NULL,
  PRIMARY KEY (`CLASSROOM_ID`),
  UNIQUE KEY `CLASSROOMNAME` (`CLASSROOMNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `COURSE` (
  `COURSE_ID` bigint(20) NOT NULL,
  `COURSENAME` varchar(255) NOT NULL,
  PRIMARY KEY (`COURSE_ID`),
  UNIQUE KEY `COURSENAME` (`COURSENAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Lecture` (
  `LECTURE_ID` bigint(20) NOT NULL,
  `DATE` date DEFAULT NULL,
  `COURSE_COURSE_ID` bigint(20) DEFAULT NULL,
  `PERIOD_PERIODCODE` varchar(10) DEFAULT NULL,
  `CLASSROOM_CLASSROOM_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`LECTURE_ID`),
  UNIQUE KEY `UNQ_Lecture_0` (`COURSE_COURSE_ID`,`DATE`),
  KEY `FK_Lecture_PERIOD_PERIODCODE_idx` (`PERIOD_PERIODCODE`),
  KEY `FK_Lecture_CLASSROOM_CLASSROOM_ID_idx` (`CLASSROOM_CLASSROOM_ID`),
  CONSTRAINT `FK_Lecture_CLASSROOM_CLASSROOM_ID` FOREIGN KEY (`CLASSROOM_CLASSROOM_ID`) REFERENCES `CLASSROOM` (`CLASSROOM_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_Lecture_COURSE_COURSE_ID` FOREIGN KEY (`COURSE_COURSE_ID`) REFERENCES `COURSE` (`COURSE_ID`),
  CONSTRAINT `FK_Lecture_PERIOD_PERIODCODE` FOREIGN KEY (`PERIOD_PERIODCODE`) REFERENCES `PERIOD` (`PERIODCODE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PERIOD` (
  `PERIODCODE` varchar(255) NOT NULL,
  `PERIODMONDAYTOFRIDAY` varchar(255) DEFAULT NULL,
  `PERIODSATURDAY` varchar(255) DEFAULT NULL,
  `USEDINMONDAYTOFRIDAY` int(11) DEFAULT NULL,
  `USEDINSATURDAY` int(11) DEFAULT NULL,
  PRIMARY KEY (`PERIODCODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PERSON` (
  `PERSON_ID` bigint(20) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `FIRSTNAME` varchar(255) NOT NULL,
  `LASTNAME` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `ROLE_ROLE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`PERSON_ID`),
  UNIQUE KEY `EMAIL` (`EMAIL`),
  KEY `FK_PERSON_ROLE_ROLE_ID` (`ROLE_ROLE_ID`),
  CONSTRAINT `FK_PERSON_ROLE_ROLE_ID` FOREIGN KEY (`ROLE_ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Registration` (
  `REGISTRATION_ID` bigint(20) NOT NULL,
  `COURSE_COURSE_ID` bigint(20) DEFAULT NULL,
  `PERSON_PERSON_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`REGISTRATION_ID`),
  UNIQUE KEY `UNQ_Registration_0` (`COURSE_COURSE_ID`,`PERSON_PERSON_ID`),
  KEY `FK_Registration_PERSON_PERSON_ID` (`PERSON_PERSON_ID`),
  CONSTRAINT `FK_Registration_COURSE_COURSE_ID` FOREIGN KEY (`COURSE_COURSE_ID`) REFERENCES `COURSE` (`COURSE_ID`),
  CONSTRAINT `FK_Registration_PERSON_PERSON_ID` FOREIGN KEY (`PERSON_PERSON_ID`) REFERENCES `PERSON` (`PERSON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ROLE` (
  `ROLE_ID` bigint(20) NOT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`),
  UNIQUE KEY `TYPE` (`TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SEQUENCE` (
  `SEQ_NAME` varchar(50) NOT NULL,
  `SEQ_COUNT` decimal(38,0) DEFAULT NULL,
  PRIMARY KEY (`SEQ_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
SELECT * FROM CNAM_Attendance_DB.CLASSROOM;

