INSERT INTO `CNAM_Attendance_DB`.`ATT_PARAMETERS` (`PARAMETERS_ID`, `ISSAE_LATITUDE`, `ISSAE_LONGITUDE`, `GOOGLE_MAPS_API`, `ACTIVE_FLG`) VALUES ('1', '33.892954', '35.497281', 'AIzaSyCv5_oKLfdKAIxGd8-iaMc_4EXOBFTIHrQ', '1');

COMMIT;

